###

GET http://localhost:5193/api/todos

###

POST localhost:5193/api/todos
Content-Type: application/json

{
    "Title": "Play Guitar",
    "Description": "Play Guitar for 30 minutes",
    "DueDate": "2029-07-01T00:00:00"
}

###

PATCH localhost:5193/api/todos/3
Content-Type: application/json

{
    "isComplete": true
}

###

PUT localhost:5193/api/todos/1
Content-Type: application/json

{
    "Title": "Test Todo",
    "Description": "Sample Description",
    "isComplete": true,
    "DueDate": "2029-07-01T00:00:00"
}

###

DELETE localhost:5193/api/todos/1